# Metryki - Problem regresji

### Import bibliotek

In [42]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [43]:
y_true = 100 + 20 * np.random.randn(50)
y_true

array([110.86768469,  90.52508269, 110.0212742 , 128.10380203,
       145.58227187,  88.31391841, 114.66467659,  86.84345444,
        96.64445239, 103.9399316 ,  84.33927918, 121.48521116,
        92.31414146,  65.03672096, 120.19016974, 114.37320869,
        31.61798645, 111.9263962 , 123.67571311, 107.80313143,
        92.23764427,  95.17623063, 108.30556686, 136.62518193,
        78.23371029, 106.65649949,  77.65365036, 111.88789715,
       112.49602268, 104.02886919, 113.33758101, 125.5399129 ,
       115.64981572, 116.68887818, 161.14327766,  77.40956685,
        96.73641516, 127.68477232, 112.01959631,  93.26607401,
       105.146898  ,  77.02436229, 121.80243813,  99.18996423,
        88.46581528,  97.97800383, 116.76526563,  92.85960841,
        98.13383342, 103.6264689 ])

In [44]:
y_pred = y_true + 10 * np.random.randn(50)
y_pred

array([122.17979844,  91.21174914, 110.18904298, 120.64173528,
       145.05132518,  93.07422675, 126.73981187,  86.49795732,
        99.97765764, 120.44226716,  76.48287878, 124.36055774,
       100.60500788,  71.31281909, 106.99230006, 118.63257907,
        23.24233341, 119.99479374, 122.20713438, 100.38229937,
       101.36417831,  83.53712319,  95.34512162, 137.27930337,
        58.14206499,  99.40503028,  71.21283062, 102.38477913,
        94.66799866, 106.11952795, 113.86638641, 127.83457879,
       115.29481995, 111.12170483, 181.04327134,  64.74960743,
        83.24926915, 116.69611525, 117.76218848, 100.23621661,
        96.74305716,  63.34462469, 115.42835085,  95.77918557,
        93.16637597, 102.46009944, 117.76343003,  90.0005759 ,
        85.69586213,  96.56046714])

In [45]:
results = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
results.head()

       y_true      y_pred
0  110.867685  122.179798
1   90.525083   91.211749
2  110.021274  110.189043
3  128.103802  120.641735
4  145.582272  145.051325

In [46]:
results['error'] = results['y_true'] - results['y_pred']
results.head()

       y_true      y_pred      error
0  110.867685  122.179798 -11.312114
1   90.525083   91.211749  -0.686666
2  110.021274  110.189043  -0.167769
3  128.103802  120.641735   7.462067
4  145.582272  145.051325   0.530947


### Interpretacja graficzna

In [47]:
def plot_regression_results(y_true, y_pred): 
    results = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
    min = results[['y_true', 'y_pred']].min().min()
    max = results[['y_true', 'y_pred']].max().max()

    fig = go.Figure(data=[go.Scatter(x=results['y_true'], y=results['y_pred'], mode='markers'),
                    go.Scatter(x=[min, max], y=[min, max])],
                    layout=go.Layout(showlegend=False, width=500, height=500,
                                     xaxis_title='y_true', 
                                     yaxis_title='y_pred',
                                     title='Regression results'))
    fig.show()
plot_regression_results(y_true, y_pred)

In [48]:
y_true = 100 + 20 * np.random.randn(1000)
y_pred = y_true + 10 * np.random.randn(1000)
results = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
results['error'] = results['y_true'] - results['y_pred']

px.histogram(results, x='error', nbins=50, width=500)

<a name='a3'></a> Mean Absolute Error - Średni błąd bezwzględny
$$MAE = \frac{1}{n}\sum_{i=1}^{n}|y_{true} - y_{pred}|$$

In [49]:
def mean_absolute_error(y_true, y_pred):
    return abs(y_true - y_pred).sum() / len(y_true)

mean_absolute_error(y_true, y_pred)

7.950190648109217

In [50]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_true, y_pred)

7.950190648109217

## Mean Squared Error - MSE - Błąd średniokwadratowy
$$MSE = \frac{1}{n}\sum_{i=1}^{n}(y_{true} - y_{pred})^{2}$$

In [51]:
def mean_squared_error(y_true, y_pred):
    return ((y_true - y_pred) ** 2).sum() / len(y_true)

mean_squared_error(y_true, y_pred)

102.00343195616705

In [52]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_true, y_pred)

102.00343195616705

## Root Mean Squared Error - RMSE - Pierwiastek błędu średniokwadratowego
$$RMSE = \sqrt{MSE}$$

In [53]:
def root_mean_squared_error(y_true, y_pred):
    return np.sqrt(((y_true - y_pred) ** 2).sum() / len(y_true))

root_mean_squared_error(y_true, y_pred)

10.099674844081221

In [54]:
np.sqrt(mean_squared_error(y_true, y_pred))

10.099674844081221

## Max Error - Błąd maksymalny

$$ME = max(|y\_true - y\_pred|)$$

In [55]:
def max_error(y_true, y_pred):
    return abs(y_true - y_pred).max()

In [56]:
max_error(y_true, y_pred)

37.92580832206728

In [57]:
from sklearn.metrics import max_error

max_error(y_true, y_pred)

37.92580832206728

## R2 score - współczynnik determinacji
$$R2\_score = 1 - \frac{\sum_{i=1}^{N}(y_{true} - y_{pred})^{2}}{\sum_{i=1}^{N}(y_{true} - \overline{y_{true}})^{2}}$$

In [61]:
from sklearn.metrics import r2_score

r2_score(y_true, y_pred)

0.743513456720191

In [59]:
def r2_score(y_true, y_pred):
    numerator = ((y_true - y_pred) ** 2).sum()
    denominator = ((y_true - y_true.mean()) ** 2).sum()
    try:
        r2 = 1 - numerator / denominator
    except ZeroDivisionError:
        print('Dzielenie przez zero')
    return r2

In [60]:
r2_score(y_true, y_pred)

0.743513456720191